version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.4-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -L https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.1.0/selenium-server-4.1.3.jar > selenium-server-4.1.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-4.1.3.jar -log test-reports/selenium.log
          background: true
      - run:
          name: Install Python requirements in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Selenium tests
          command: |
            . venv/bin/activate
            python __main__.py